<?php
/**
 * Copyright (c) 2011 Rodrigo Saiz Camarero [rodrigo at regoluna.com]
 * Licensed under the GPL3 license
 *
 * @package regoluna_mail_queue
 * @author Rodrigo Saiz Camarero <rodrigo@regoluna.com>
 */
$dictionary['reg_qmail'] = array(
  'table'           => 'reg_qmail',
  'audited'         => true,
  'fields'          => array(
    'type'          => array(
      'required'                  => false,
      'name'                      => 'type',
      'vname'                     => 'LBL_TYPE',
      'type'                      => 'varchar',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => '25',
    ),
    'template_file' => array(
      'required'                  => false,
      'name'                      => 'template_file',
      'vname'                     => 'LBL_TEMPLATE_FILE',
      'type'                      => 'varchar',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => '100',
    ),
    'variables'     => array(
      'required'                  => false,
      'name'                      => 'variables',
      'vname'                     => 'LBL_VARIABLES',
      'type'                      => 'text',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => 'Introduzca una lista de palabras separadas por comas.',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'studio'                    => 'visible',
    ),
    'recipient'     => array(
      'required'                  => false,
      'name'                      => 'recipient',
      'vname'                     => 'LBL_RECIPIENT',
      'type'                      => 'varchar',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => '150',
    ),
    'in_queue'      => array(
      'required'                  => false,
      'name'                      => 'in_queue',
      'vname'                     => 'LBL_STATUS',
      'dbtype'                    => 'int',
      'type'                      => 'enum',
      'massupdate'                => true,
      'default'                   => '1',
      'importable'                => false,
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      //'len' => 2,
      'options'                   => 'reg_qmail_in_queue',
      
      'studio'                    => false,
    ),
    'error_message' => array(
      'required'                  => false,
      'name'                      => 'error_message',
      'vname'                     => 'LBL_ERROR_MESSAGE',
      'type'                      => 'varchar',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => '100',
    ),
    'sent_date'     => array(
      'required'                  => false,
      'name'                      => 'sent_date',
      'vname'                     => 'LBL_SENT_DATE',
      'type'                      => 'datetime',
      'dbtype'                    => 'datetime',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'false',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
    ),

    //
    // "Flex Relate" fields
    //
    'parent_name'   => array(
      'required'                  => false,
      'source'                    => 'non-db',
      'name'                      => 'parent_name',
      'vname'                     => 'LBL_FLEX_RELATE',
      'type'                      => 'parent',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'true',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => 25,
      'options'                   => 'parent_type_display',
      'studio'                    => 'visible',
      'type_name'                 => 'parent_type',
      'id_name'                   => 'parent_id',
      'parent_type'               => 'record_type_display',
    ),
    'parent_type'   => array(
      'required'                  => false,
      'name'                      => 'parent_type',
      'vname'                     => 'LBL_PARENT_TYPE',
      'type'                      => 'parent_type',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'true',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => 100,
      'dbType'                    => 'varchar',
      'studio'                    => 'hidden',
    ),
    'parent_id'     => array(
      'required'                  => false,
      'name'                      => 'parent_id',
      'vname'                     => 'LBL_PARENT_ID',
      'type'                      => 'id',
      'massupdate'                => 0,
      'comments'                  => '',
      'help'                      => '',
      'importable'                => 'true',
      'duplicate_merge'           => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited'                   => 0,
      'reportable'                => 0,
      'len'                       => 36,
    ),

  ),
  'relationships'   => array(
  ),
  'optimistic_lock' => true,
  'indices'         => array(
    array('name' => 'idx_in_queue', 'type' => 'index', 'fields' => array('in_queue')),
  ),
);
if (!class_exists('VardefManager')) {
  require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('reg_qmail', 'reg_qmail', array('basic'));
